Update Uninstaller

diff --git a/Uninstaller b/Uninstaller
--- a/Uninstaller
+++ b/Uninstaller
@@ -6,10 +6,10 @@ BLUE='\033[1;34m'
 YELLOW='\033[1;33m'
 X='\033[0m'
 
-[ -z "${BASH_VERSION:-}" ] && echo "${RED}[*] This script must be run with bash" && exit 1
+[ -z "${BASH_VERSION:-}" ] && echo "${RED}[!] This script must be run with bash" && exit 1
 
 if [[ -z "$PREFIX" || -z "$TERMUX_VERSION" ]]; then
-    echo -e "${RED}[*] This script must be ran in Termux${X}"
+    echo -e "${RED}[!] This script must be ran in Termux${X}"
     exit 1
 fi
 
@@ -24,10 +24,10 @@ for f in "$RISH_BIN" "$DEX_BIN"; do
         rm -f "$f" && echo -e "${GREEN}[*] $(basename "$f") uninstalled successfully${X}"
         any_deleted=true
     else
-        echo -e "${YELLOW}[*] $(basename "$f") not found${X}"
+        echo -e "${YELLOW}[-] $(basename "$f") not found${X}"
     fi
 done
 
 if [ "$any_deleted" = false ]; then
-    echo -e "${BLUE}[*] No rish files found${X}"
+    echo -e "${BLUE}[+] No rish files found${X}"
 fi
