Refactor Uninstaller script for improved logic

diff --git a/Uninstaller b/Uninstaller
--- a/Uninstaller
+++ b/Uninstaller
@@ -1,22 +1,30 @@
 #!/bin/bash
 
-RISH_BIN="/data/data/com.termux/files/usr/bin/rish"
-DEX_BIN="/data/data/com.termux/files/usr/bin/rish_shizuku.dex"
-
 RED='\033[1;31m'
 GREEN='\033[1;32m'
 BLUE='\033[1;34m'
+YELLOW='\033[1;33m'
 X='\033[0m'
 
-any_exist=false
+if [[ -z "$PREFIX" || -z "$TERMUX_VERSION" ]]; then
+    echo -e "${RED}[*] This script must be ran in Termux${X}"
+    exit 1
+fi
+
+RISH_BIN="/data/data/com.termux/files/usr/bin/rish"
+DEX_BIN="/data/data/com.termux/files/usr/bin/rish_shizuku.dex"
+
+any_deleted=false
 
 for f in "$RISH_BIN" "$DEX_BIN"; do
     if [ -f "$f" ]; then
         rm -f "$f" && echo -e "${GREEN}[*] $(basename "$f") deleted successfully${X}"
-        any_exist=true
+        any_deleted=true
+    else
+        echo -e "${YELLOW}[*] $(basename "$f") not found${X}"
     fi
 done
 
-if [ "$any_exist" = false ]; then
-    echo -e "${BLUE}[*] rish files not installed${X}"
+if [ "$any_deleted" = false ]; then
+    echo -e "${BLUE}[*] No rish files were installed${X}"
 fi
